stages:
  - tarball

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

prepare tarball:
  stage: tarball
  image: registry.gitlab.com/lfortran/ci-images:prepare-1.7.0
  variables:
    # Both of these variables are needed, so that `git describe` can see the
    # recent tags
    GIT_FETCH_EXTRA_FLAGS: --tags --prune --prune-tags
    GIT_DEPTH: 0 # fetch all commits and tags
  script:
    - echo "OK"
