# Azure Pipelines CI
# Documentation of the syntax:
# https://aka.ms/yaml

jobs:
  - job: macOS
    pool:
      # List of preinstalled software on the macOS image:
      # https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md
      vmImage: 'macOS-10.13'
    steps:
    - script: ci/azure_status.sh running
      env:
        TOKEN_STATUS: $(TOKEN_STATUS)
        COMMIT_ID: $(Build.SourceVersion)
        BUILD_ID: $(Build.BuildId)
      displayName: Set commit status to running
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - bash: sudo chown -R $USER $CONDA
      displayName: Take ownership of conda installation
    - script: ci/azure_install_macos.sh
      displayName: 'Install prerequisites'
    - script: ci/azure_status.sh
      condition: always()
      env:
        TOKEN_STATUS: $(TOKEN_STATUS)
        COMMIT_ID: $(Build.SourceVersion)
        BUILD_ID: $(Build.BuildId)
      displayName: Set commit status (success/failed)
