# This file was automatically generated by the LFortran compiler.
# Editing by hand is discouraged.

from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
cdef extern from "module_variable_wrapper.h":
  cdef void module_variable_get_a(int32_t *a)
  cdef void module_variable_set_a(int32_t *a)
